import { NextResponse } from "next/server";
import { Resend } from "resend";

export async function POST(request: Request) {
  try {
    const { name, phone, email, facilitySize, serviceType, message, zipCode } = await request.json();

    // Verify required environment variables
    const apiKey = process.env.RESEND_API_KEY;
    const destEmail = process.env.DESTINATION_EMAIL || "allstatecustomercare1@gmail.com";

    if (!apiKey) {
      console.error("Missing RESEND_API_KEY environment variable");
      return NextResponse.json(
        { error: "Mail configuration error. Please contact administration." },
        { status: 500 }
      );
    }

    const resend = new Resend(apiKey);

    // Human-readable service type labels
    const serviceLabels: Record<string, string> = {
      office: "Office Cleaning",
      janitorial: "Janitorial Services",
      floors: "Floor Stripping & Waxing",
      maintenance: "Facility Maintenance & Repairs",
    };
    const selectedService = serviceType ? (serviceLabels[serviceType] || serviceType) : null;

    // Send the email via Resend API
    const isTopForm = !!zipCode;
    const result = await resend.emails.send({
      from: "Allstate Maintenance <onboarding@resend.dev>",
      to: destEmail,
      subject: isTopForm 
        ? `New Free Estimate Request (${zipCode}) - ${name}`
        : `New Commercial Quote Request - ${name}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px; background-color: #ffffff;">
          <h2 style="color: #3b84f6; margin-top: 0; border-bottom: 2px solid #3b84f6; padding-bottom: 10px;">
            ${isTopForm ? "New Quick Estimate Request" : "New Commercial Maintenance Lead"}
          </h2>
          <p style="font-size: 16px; color: #0f172a; margin-bottom: 20px;">
            You have received a new lead request from the Allstate website.
          </p>
          
          <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
            <tr style="background-color: #f8fafc;">
              <td style="padding: 10px; font-weight: bold; border: 1px solid #e2e8f0; width: 35%;">Business / Client Name:</td>
              <td style="padding: 10px; border: 1px solid #e2e8f0;">${name}</td>
            </tr>
            <tr>
              <td style="padding: 10px; font-weight: bold; border: 1px solid #e2e8f0;">Phone Number:</td>
              <td style="padding: 10px; border: 1px solid #e2e8f0;"><a href="tel:${phone}">${phone}</a></td>
            </tr>
            <tr style="background-color: #f8fafc;">
              <td style="padding: 10px; font-weight: bold; border: 1px solid #e2e8f0;">Email Address:</td>
              <td style="padding: 10px; border: 1px solid #e2e8f0;"><a href="mailto:${email}">${email}</a></td>
            </tr>
            ${zipCode ? `
            <tr>
              <td style="padding: 10px; font-weight: bold; border: 1px solid #e2e8f0;">ZIP Code:</td>
              <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: bold; color: #3b84f6;">${zipCode}</td>
            </tr>
            ` : ""}
            ${facilitySize ? `
            <tr style="background-color: #f8fafc;">
              <td style="padding: 10px; font-weight: bold; border: 1px solid #e2e8f0;">Facility Size (Sq. Ft.):</td>
              <td style="padding: 10px; border: 1px solid #e2e8f0;">${facilitySize}</td>
            </tr>
            ` : ""}
            ${selectedService ? `
            <tr>
              <td style="padding: 10px; font-weight: bold; border: 1px solid #e2e8f0;">Required Service:</td>
              <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: bold; color: #3b84f6;">${selectedService}</td>
            </tr>
            ` : ""}
          </table>

          ${!isTopForm ? `
          <div style="margin-top: 20px;">
            <h4 style="margin-bottom: 5px; color: #0f172a;">Additional Details & Requests:</h4>
            <div style="padding: 15px; border: 1px solid #e2e8f0; border-radius: 6px; background-color: #f8fafc; color: #475569; font-style: italic; white-space: pre-wrap;">
              ${message || "No additional comments provided."}
            </div>
          </div>
          ` : ""}
          
          <div style="margin-top: 30px; text-align: center; font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 15px;">
            This lead was automatically generated by the Allstate Building & Office Maintenance portal.
          </div>
        </div>
      `,
    });

    if (result.error) {
      console.error("Resend API Error:", result.error);
      return NextResponse.json(
        { error: result.error.message || "Failed to send email via Resend." },
        { status: 400 }
      );
    }

    return NextResponse.json({ success: true, id: result.data?.id });
  } catch (error: any) {
    console.error("Error sending email:", error);
    return NextResponse.json(
      { error: error?.message || "Internal server error. Failed to send email." },
      { status: 500 }
    );
  }
}
